version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
    main: "./cmd"
    binary: savac
archives:
  - formats: ['zip']
    name_template: '{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_SHA256SUMS'
  algorithm: sha256
sboms:
  - artifacts: archive
