/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package fake_vps

import (
	"log"
	"net/http"

	sw "github.com/g1eng/savac/testutil/fake_vps/fake_server"
	"github.com/g1eng/savac/testutil/test_parameters"
)

func StartFakeServer(endpoint string) error {
	routes := sw.ApiHandleFunctions{}
	log.Printf("Mock server started")
	router := sw.NewRouter(routes)

	return router.Run(endpoint)
}

type FaultServer struct{}

func (m *FaultServer) ServeHTTP(w http.ResponseWriter, _ *http.Request) {
	w.WriteHeader(http.StatusTooManyRequests)
	w.Write([]byte(test_parameters.Fixture429Text)) // nolint
}

func StartFaultServer(host string) (*http.Server, error) {
	server := http.Server{
		Addr:              host,
		Handler:           &FaultServer{},
		TLSConfig:         nil,
		ReadTimeout:       0,
		ReadHeaderTimeout: 0,
		WriteTimeout:      0,
		IdleTimeout:       0,
		MaxHeaderBytes:    0,
		TLSNextProto:      nil,
		ConnState:         nil,
		ErrorLog:          nil,
		BaseContext:       nil,
		ConnContext:       nil,
	}
	return &server, server.ListenAndServe()
}
