/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

import (
	sakuravps "github.com/g1eng/sakura_vps_client_go"
	"github.com/gin-gonic/gin"
)

type DiscAPI struct {
}

// GetDiscList Get /vps/api/v7/discs
// ディスク情報一覧を取得する
func (api *DiscAPI) GetDiscList(c *gin.Context) {
	res := sakuravps.NewGetDiscList200ResponseWithDefaults()
	d := sakuravps.NewDiscWithDefaults()
	res.Results = append(res.Results, *d)
	c.JSON(200, res)
}
