/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

import (
	sakuravps "github.com/g1eng/sakura_vps_client_go"
	"github.com/gin-gonic/gin"
)

type ZoneAPI struct {
}

// GetZoneList Get /vps/api/v7/zones
// ゾーン情報一覧を取得する
func (api *ZoneAPI) GetZoneList(c *gin.Context) {
	res := sakuravps.NewGetZoneList200ResponseWithDefaults()
	z := sakuravps.NewZoneWithDefaults()
	res.Results = append(res.Results, *z)
	c.JSON(200, res)
}
