/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type ServerIpv4 struct {

	// アドレス
	Address string `json:"address"`

	// サブネットマスク
	Netmask string `json:"netmask"`

	// ゲートウェイのアドレス
	Gateway string `json:"gateway"`

	// ネームサーバーのアドレスリスト
	Nameservers []string `json:"nameservers"`

	// 標準ホスト名
	Hostname string `json:"hostname"`

	// 逆引きホスト名
	Ptr string `json:"ptr"`
}
