/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type ServerInterface struct {

	// id
	Id int32 `json:"id"`

	// NIC名称
	Device string `json:"device"`

	// グローバルネットワークと接続可能か
	ConnectableToGlobalNetwork bool `json:"connectable_to_global_network"`

	// インターフェースの接続先
	ConnectTo *string `json:"connect_to"`

	// MACアドレス
	Mac string `json:"mac"`

	// スイッチID
	SwitchId *int32 `json:"switch_id"`
}
