/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type Zone struct {

	// id
	Id int32 `json:"id"`

	// ゾーンコード * tk1 東京第1 * tk2 東京第2 * tk3 東京第3 * os1 大阪第1 * os2 大阪第2 * os3 大阪第3 * is1 石狩第1
	Code string `json:"code"`

	// ゾーン名称
	Name string `json:"name"`

	// ローカルネットワーク接続が可能かどうか
	CanUseLocal bool `json:"can_use_local"`

	// ハイブリッド接続が利用可能かどうか
	CanUseHybrid bool `json:"can_use_hybrid"`
}
