/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type GetZoneList200Response struct {

	// データ総数
	Count int32 `json:"count"`

	// 次のページへのURL
	Next *string `json:"next"`

	// 前のページへのURL
	Previous *string `json:"previous"`

	Results []Zone `json:"results"`
}
