/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type ApiKey struct {

	// id
	Id int32 `json:"id"`

	// 名前
	Name string `json:"name"`

	// ロールID
	Role int32 `json:"role"`

	// APIのアクセストークン。APIキー作成時とトークンローテーション時以外は情報を`*`でマスクして返します。
	Token string `json:"token"`
}
