/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type InvalidParameterDetailInner struct {

	// エラー内容を示す簡潔な識別子
	Code string `json:"code,omitempty"`

	Message string `json:"message,omitempty"`
}
