/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type PostSwitch201Response struct {

	// id
	Id int32 `json:"id"`

	// 名前
	Name string `json:"name"`

	// 説明
	Description string `json:"description"`

	// スイッチコード
	SwitchCode string `json:"switch_code"`

	Zone PostSwitch201ResponseZone `json:"zone"`

	// 接続されているサーバーのインターフェースid
	ServerInterfaces []int32 `json:"server_interfaces"`

	// 接続されている追加ストレージ（NFS）のインターフェースid
	NfsServerInterfaces []int32 `json:"nfs_server_interfaces"`

	// 接続されている外部接続の情報
	ExternalConnection *map[string]interface{} `json:"external_connection"`
}
