/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

// ServerMonitoringSettingsNotificationIncomingWebhook - incoming webhookでの通知の設定
type ServerMonitoringSettingsNotificationIncomingWebhook struct {

	// 通知のON/OFF * true 通知ON * false 通知OFF
	Enabled bool `json:"enabled"`

	// 通知先のWebhooksURL。 Slack、Discord、Microsoft TeamsのIncoming WebHooksにのみ対応しています。 指定できるURLは各サービスのWebhook URL(https://hooks.slack.com/services/_* など)の形式に制限されています。 Discordの場合は[Slack互換のWebhook URL](https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook)を指定してください。
	WebhooksUrl *string `json:"webhooks_url"`

	// slackのteam name。VPSコントロールパネルの「Slackと自動で連携をする」を利用した場合に設定されます。
	SlackTeamName string `json:"slack_team_name"`

	// slackのchannel name。VPSコントロールパネルの「Slackと自動で連携をする」を利用した場合に設定されます。
	SlackChannelName string `json:"slack_channel_name"`
}
