/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

// ProblemDetails400Errors - 入力値に対するエラーを構造化した情報 (code`invalid`の場合のみ) * `non_field_errors` - リクエスト全体に起因した(単一項目でない)エラー内容 * `*` - 対応した入力項目ごとのエラー内容
type ProblemDetails400Errors struct {
	NonFieldErrors []InvalidParameterDetailInner `json:"non_field_errors,omitempty"`
}
