/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type SwitchExternalConnectionServicesInner struct {

	// サービスカテゴリー
	ServiceCategory string `json:"service_category"`

	// サービス名
	ServiceName string `json:"service_name"`

	// スイッチコード
	SwitchCode string `json:"switch_code"`
}
