/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type Role struct {

	// id
	Id int32 `json:"id"`

	// 名前
	Name string `json:"name"`

	// 説明
	Description string `json:"description"`

	// 利用できる権限を制限するか
	PermissionFiltering string `json:"permission_filtering"`

	// 利用できる権限。permission_filteringがenabledの場合のみ指定可能。**権限の一覧を取得する**`/permissions`のcode値を指定します。
	AllowedPermissions []string `json:"allowed_permissions"`

	// 利用できるリソースを制限するか
	ResourceFiltering string `json:"resource_filtering"`

	AllowedResources *RoleAllowedResources `json:"allowed_resources"`
}
