/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type Limitation struct {

	// CPUリソースの制限可否
	CpuPerformanceLimit string `json:"cpu_performance_limit,omitempty"`

	// ネットワーク帯域の制限可否
	NetworkBandwidthLimit string `json:"network_bandwidth_limit,omitempty"`

	// OP25Bの可否
	OutboundPort25Blocking string `json:"outbound_port_25_blocking,omitempty"`

	// ストレージのIOPSの制限可否
	StorageIopsLimit string `json:"storage_iops_limit,omitempty"`
}
