/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type PostServerShutdownRequest struct {

	// 強制停止を行うか
	Force bool `json:"force,omitempty"`
}
