/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type ServerMonitoring struct {

	// id
	Id int32 `json:"id"`

	// 名前
	Name string `json:"name"`

	// 説明
	Description string `json:"description"`

	// 監視リソースID
	MonitoringResourceId string `json:"monitoring_resource_id"`

	// 更新ステータス * waiting 更新待ち * updating 更新中 * completed 更新完了 * error 更新エラー
	UpdateStatus string `json:"update_status"`

	Settings ServerMonitoringSettings `json:"settings"`
}
