/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type ServerStorageInner struct {

	// ポート番号
	Port int32 `json:"port"`

	// 種別
	Type string `json:"type"`

	// ストレージ容量(GiB)
	SizeGibibytes int32 `json:"size_gibibytes"`
}
