/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type ServerMonitoringSettings struct {

	// 監視のON/OFF * true 監視ON * false 監視OFF
	Enabled bool `json:"enabled"`

	HealthCheck ServerMonitoringSettingsHealthCheck `json:"health_check"`

	Notification ServerMonitoringSettingsNotification `json:"notification"`
}
