/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type ServerIpv6 struct {

	// アドレス
	Address *string `json:"address"`

	// プレフィックス長
	Prefixlen *int32 `json:"prefixlen"`

	// ゲートウェイのアドレス
	Gateway *string `json:"gateway"`

	// ネームサーバーのアドレスリスト
	Nameservers []string `json:"nameservers"`

	// 標準ホスト名
	Hostname *string `json:"hostname"`

	// 逆引きホスト名
	Ptr *string `json:"ptr"`
}
