/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

import (
	"time"
)

type ServerMonitoringHealth struct {

	// 最終監視日時
	LastCheckedAt *time.Time `json:"last_checked_at"`

	// ステータス   * healthy 正常   * unhealthy 異常
	Status *string `json:"status"`

	// 最終ステータス変更日時
	LastStatusChangedAt *time.Time `json:"last_status_changed_at"`
}
