/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type PostNfsServerChangeIpv4Request struct {

	// ipv4アドレス
	Address string `json:"address"`

	// ネットマスク
	Netmask string `json:"netmask"`
}
