/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

// RoleAllowedResources - 利用できるリソース。resource_filteringがenabledの場合のみ指定可能。
type RoleAllowedResources struct {

	// 利用できるサーバーのid
	Servers []int32 `json:"servers,omitempty"`

	// 利用できるスイッチのid
	Switches []int32 `json:"switches,omitempty"`

	// 利用できるNFSのid
	NfsServers []int32 `json:"nfs_servers,omitempty"`
}
