/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type Permission struct {

	// 権限のcode
	Code string `json:"code"`

	// 名前
	Name string `json:"name"`

	// 権限のカテゴリー
	Category string `json:"category"`
}
