/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

// ServerContract - 契約情報
type ServerContract struct {

	// プランコード
	PlanCode int32 `json:"plan_code"`

	// プラン名
	PlanName string `json:"plan_name"`

	// サービスコード
	ServiceCode string `json:"service_code"`
}
