/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type NfsStorageInfo struct {

	// ストレージの空き容量（KiB）
	FreeSpaceKib int32 `json:"free_space_kib"`

	// ストレージの使用率
	UsagePercentage int32 `json:"usage_percentage"`

	// ストレージの全容量（KiB）
	CapacityKib int32 `json:"capacity_kib"`

	// ストレージの使用容量（KiB）
	UsageKib int32 `json:"usage_kib"`
}
