/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type HealthCheckHttp struct {

	// ポート番号
	Port int32 `json:"port"`

	// 監視用HTTPリクエストのHostヘッダ   RFCの定義に基づいて下記の制限をかけています * ラベルは2つ以上必要 * 各ラベルについて   * 利用できる文字     * 半角数字 0～9     * 半角英小文字 a～z     * 半角記号 -   * 両端が-でないこと   * -が2つ以上続かないこと。ただしpunycodeの接頭辞`xn--`を除く   * 下記パターン(RFCなどで予約または禁止されているパターン)と一致しないこと     * isatap     * wpad     * example     * example0～example9 * 最後のラベルについて   * 利用できる文字     * 半角英小文字 a～z   * 下記のパターン(RFC予約済みのDNS名)と一致しないこと     * test     * localhost
	Host *string `json:"host"`

	// 監視対象のパス * 利用できる文字    * 半角数字 0～9   * 半角英字 A～Z、a～z   * 半角記号 _./~%?=-&
	Path string `json:"path"`

	// ベーシック認証のユーザー名 * 利用できる文字    * 半角数字 0～9   * 半角英字 A～Z、a～z   * 半角記号 _.-+!@
	BasicAuthUsername *string `json:"basic_auth_username"`

	// ベーシック認証のパスワード * 利用できる文字    * 半角数字 0～9   * 半角英字 A～Z、a～z   * 半角記号 !#$%&()*+,-./:<=>?@[]^_`{|}~
	BasicAuthPassword *string `json:"basic_auth_password"`

	// 正常と見なすHTTPステータスコード
	Status int32 `json:"status"`

	// チェック間隔(分)
	IntervalMinutes int32 `json:"interval_minutes"`

	// 監視方法
	Protocol string `json:"protocol"`
}
