/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type ProblemDetails400 struct {

	// エラー内容を示す簡潔な識別子 * `invalid` - 不正なリクエスト値,リクエスト値が妥当でない * `parse_error` - 不正な形式,リクエスト値を読み取ることができない * `bad_request` - リクエストの内容に何らかの問題がある
	Code string `json:"code,omitempty"`

	// エラーの内容
	Message string `json:"message,omitempty"`

	Errors *ProblemDetails400Errors `json:"errors,omitempty"`
}
