/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type PutServerIpv4Ptr200Response struct {

	// 逆引きホスト名
	Ptr string `json:"ptr"`
}
