/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type ServerMonitoringSettingsNotification struct {
	Email ServerMonitoringSettingsNotificationEmail `json:"email"`

	IncomingWebhook ServerMonitoringSettingsNotificationIncomingWebhook `json:"incoming_webhook"`

	// 再通知間隔(時間)
	IntervalHours int32 `json:"interval_hours"`
}
