/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type PostSwitchRequest struct {

	// 名前
	Name string `json:"name"`

	// 説明
	Description string `json:"description"`

	// ゾーンコード * tk2 東京第2 * tk3 東京第3 * os3 大阪第3 * is1 石狩第1
	ZoneCode string `json:"zone_code"`
}
