/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type HealthCheckPing struct {

	// 監視方法
	Protocol string `json:"protocol"`

	// チェック間隔(分)
	IntervalMinutes int32 `json:"interval_minutes"`
}
