/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type NfsServer struct {

	// id
	Id int32 `json:"id"`

	// 名前
	Name string `json:"name"`

	// 説明
	Description string `json:"description"`

	// サービス状況 * in_preparation 準備中 * on_trial お試し中 * link_down_on_trial お試し中（一時停止） * in_use 利用中 * link_down 一時停止中
	ServiceStatus string `json:"service_status"`

	// 設定状況 * done 設定完了 * in_update 設定更新中 * failed 設定更新失敗
	SettingStatus string `json:"setting_status"`

	// ストレージ情報
	Storage []NfsServerStorageInner `json:"storage"`

	Zone ServerZone `json:"zone"`

	Ipv4 NfsServerIpv4 `json:"ipv4"`

	Contract NfsServerContract `json:"contract"`

	// 電源ステータス * power_on 電源ON * in_shutdown シャットダウン中 * power_off 電源OFF * unknown 不明（電源状態を取得できない） このエンドポイントが返す電源ステータスはキャッシュされた情報のため、最新の正確な電源ステータスではない場合があります
	PowerStatus string `json:"power_status"`
}
