/*
 * さくらのVPS APIドキュメント
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.5.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package helper

type Server struct {

	// id
	Id int32 `json:"id"`

	// 名前
	Name string `json:"name"`

	// 説明
	Description string `json:"description"`

	// サービスタイプ
	ServiceType string `json:"service_type"`

	// サービス状況 * on_trial お試し中 * link_down_on_trial お試し中（一時停止） * in_use 利用中 * link_down 一時停止中
	ServiceStatus string `json:"service_status"`

	// CPUコア数
	CpuCores int32 `json:"cpu_cores"`

	// メモリ容量(MiB)
	MemoryMebibytes int32 `json:"memory_mebibytes"`

	// ストレージ情報
	Storage []ServerStorageInner `json:"storage"`

	Zone ServerZone `json:"zone"`

	// オプション（追加ソフトウェア）
	Options []string `json:"options"`

	// プランの世代
	Version string `json:"version"`

	Ipv4 ServerIpv4 `json:"ipv4"`

	Ipv6 ServerIpv6 `json:"ipv6"`

	Contract ServerContract `json:"contract"`

	// 電源ステータス * power_on 電源ON * in_shutdown シャットダウン中 * power_off 電源OFF * installing OSインストール中 * in_scaleup スケールアップ中 * migration サーバー移行作業中 * unknown 不明（電源状態を取得できない） このエンドポイントが返す電源ステータスはキャッシュされた情報のため、最新の正確な電源ステータスが必要な場合は **サーバーの電源状態を取得する**`/servers/{server_id}/power-status`をご利用ください
	PowerStatus string `json:"power_status"`
}
